-- =============================================================================
-- Spring API Ecommerce - full schema DDL (PostgreSQL)
--
-- Hand-derived from the JPA entities under com.example.ecommerce.model to match
-- exactly what Hibernate's ddl-auto:update would create for the `prod` profile.
-- This is a standalone reference/bootstrap script - the app itself does NOT run
-- this automatically; Hibernate still manages the schema at runtime via
-- ddl-auto:update (see src/main/resources/application.yml). Use this when you
-- want to stand up the schema by hand (e.g. against a shared Postgres instance)
-- without booting the app first.
--
-- Run with:  psql -h <host> -U <user> -d <database> -f sql/schema.sql
-- =============================================================================

-- ── users ────────────────────────────────────────────────────────────────
CREATE TABLE users (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email             VARCHAR(255) NOT NULL UNIQUE,
    password_hash     VARCHAR(255) NOT NULL,
    full_name         VARCHAR(100) NOT NULL,
    phone             VARCHAR(20),
    account_status    VARCHAR(20) NOT NULL CHECK (account_status IN ('ACTIVE','SUSPENDED','BANNED','DELETED')),
    email_verified    BOOLEAN NOT NULL,
    email_verified_at TIMESTAMP,
    last_login_at     TIMESTAMP,
    is_buyer          BOOLEAN NOT NULL,
    is_seller         BOOLEAN NOT NULL,
    created_at        TIMESTAMP NOT NULL,
    updated_at        TIMESTAMP NOT NULL,
    deleted_at        TIMESTAMP
);
CREATE INDEX idx_users_email ON users (email);
CREATE INDEX idx_users_account_status ON users (account_status);
CREATE INDEX idx_users_created_at ON users (created_at);

-- ── seller_profiles ──────────────────────────────────────────────────────
CREATE TABLE seller_profiles (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                BIGINT NOT NULL UNIQUE REFERENCES users (id),
    shop_name              VARCHAR(100) NOT NULL UNIQUE,
    shop_description       TEXT,
    shop_logo_url          VARCHAR(500),
    seller_rating          NUMERIC(3,2) NOT NULL,
    total_products_sold    INTEGER NOT NULL,
    total_revenue          NUMERIC(12,2) NOT NULL,
    verification_status    VARCHAR(20) NOT NULL CHECK (verification_status IN ('UNVERIFIED','VERIFIED','REJECTED')),
    bank_account_encrypted VARCHAR(500),
    commission_rate        NUMERIC(5,2) NOT NULL,
    shop_created_at        TIMESTAMP NOT NULL,
    updated_at             TIMESTAMP NOT NULL
);
CREATE INDEX idx_seller_profiles_verification_status ON seller_profiles (verification_status);
CREATE INDEX idx_seller_profiles_seller_rating ON seller_profiles (seller_rating);
CREATE INDEX idx_seller_profiles_shop_name ON seller_profiles (shop_name);

-- ── addresses ────────────────────────────────────────────────────────────
CREATE TABLE addresses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users (id),
    full_name       VARCHAR(100) NOT NULL,
    phone           VARCHAR(20) NOT NULL,
    street_address  VARCHAR(255) NOT NULL,
    city            VARCHAR(100) NOT NULL,
    state_province  VARCHAR(100) NOT NULL,
    postal_code     VARCHAR(20) NOT NULL,
    country         VARCHAR(100) NOT NULL,
    is_default      BOOLEAN NOT NULL,
    address_type    VARCHAR(20) NOT NULL CHECK (address_type IN ('HOME','WORK','OTHER')),
    created_at      TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP NOT NULL
);
CREATE INDEX idx_addresses_user_id ON addresses (user_id);
CREATE INDEX idx_addresses_is_default ON addresses (user_id, is_default);

-- ── categories (self-referencing) ───────────────────────────────────────
CREATE TABLE categories (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id             BIGINT REFERENCES categories (id),
    category_name         VARCHAR(100) NOT NULL,
    category_description  TEXT,
    is_active             BOOLEAN NOT NULL,
    display_order         INTEGER NOT NULL,
    created_at            TIMESTAMP NOT NULL,
    updated_at            TIMESTAMP NOT NULL,
    CONSTRAINT uniq_name_per_parent UNIQUE (parent_id, category_name)
);
CREATE INDEX idx_categories_parent_id ON categories (parent_id);
CREATE INDEX idx_categories_is_active ON categories (is_active);

-- ── products ─────────────────────────────────────────────────────────────
CREATE TABLE products (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id             BIGINT NOT NULL REFERENCES seller_profiles (id),
    category_id           BIGINT NOT NULL REFERENCES categories (id),
    product_name          VARCHAR(255) NOT NULL,
    product_description   TEXT,
    sku                   VARCHAR(100) NOT NULL UNIQUE,
    price                 NUMERIC(10,2) NOT NULL,
    currency              VARCHAR(3) NOT NULL,
    stock_quantity        INTEGER NOT NULL,
    product_status        VARCHAR(20) NOT NULL CHECK (product_status IN ('ACTIVE','INACTIVE','DELISTED')),
    discount_percentage   NUMERIC(5,2) NOT NULL,
    discount_valid_until  TIMESTAMP,
    average_rating        NUMERIC(3,2) NOT NULL,
    total_reviews         INTEGER NOT NULL,
    views_count           INTEGER NOT NULL,
    created_at            TIMESTAMP NOT NULL,
    updated_at            TIMESTAMP NOT NULL
);
CREATE INDEX idx_products_seller_id ON products (seller_id);
CREATE INDEX idx_products_category_id ON products (category_id);
CREATE INDEX idx_products_product_status ON products (product_status);
CREATE INDEX idx_products_sku ON products (sku);
CREATE INDEX idx_products_category_status ON products (category_id, product_status);
CREATE INDEX idx_products_rating_status ON products (average_rating DESC, product_status);

-- ── product_images ───────────────────────────────────────────────────────
CREATE TABLE product_images (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id     BIGINT NOT NULL REFERENCES products (id),
    image_url      VARCHAR(500) NOT NULL,
    alt_text       VARCHAR(200),
    display_order  INTEGER NOT NULL,
    uploaded_at    TIMESTAMP NOT NULL
);
CREATE INDEX idx_product_images_product_id ON product_images (product_id);
CREATE INDEX idx_product_images_display_order ON product_images (product_id, display_order);

-- ── carts ────────────────────────────────────────────────────────────────
CREATE TABLE carts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL UNIQUE REFERENCES users (id),
    created_at       TIMESTAMP NOT NULL,
    last_updated_at  TIMESTAMP NOT NULL,
    expires_at       TIMESTAMP NOT NULL,
    CONSTRAINT unique_active_cart_per_user UNIQUE (user_id)
);
CREATE INDEX idx_carts_user_id ON carts (user_id);
CREATE INDEX idx_carts_expires_at ON carts (expires_at);

-- ── cart_items ───────────────────────────────────────────────────────────
CREATE TABLE cart_items (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id        BIGINT NOT NULL REFERENCES carts (id),
    product_id     BIGINT NOT NULL REFERENCES products (id),
    quantity       INTEGER NOT NULL,
    price_at_add   NUMERIC(10,2) NOT NULL,
    added_at       TIMESTAMP NOT NULL,
    CONSTRAINT unique_product_per_cart UNIQUE (cart_id, product_id)
);
CREATE INDEX idx_cart_items_cart_id ON cart_items (cart_id);
CREATE INDEX idx_cart_items_product_id ON cart_items (product_id);

-- ── orders ───────────────────────────────────────────────────────────────
CREATE TABLE orders (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number             VARCHAR(50) NOT NULL UNIQUE,
    buyer_id                 BIGINT NOT NULL REFERENCES users (id),
    seller_id                BIGINT REFERENCES seller_profiles (id),
    order_date               TIMESTAMP NOT NULL,
    order_status             VARCHAR(20) NOT NULL CHECK (order_status IN ('PENDING','CONFIRMED','PACKED','SHIPPED','DELIVERED','CANCELLED','RETURNED')),
    total_amount             NUMERIC(12,2) NOT NULL,
    shipping_address_id      BIGINT NOT NULL REFERENCES addresses (id),
    billing_address_id       BIGINT REFERENCES addresses (id),
    shipping_method          VARCHAR(50),
    tracking_number          VARCHAR(100),
    estimated_delivery_date  DATE,
    actual_delivery_date     DATE,
    return_initiated_at      TIMESTAMP,
    notes                    TEXT,
    created_at               TIMESTAMP NOT NULL,
    updated_at               TIMESTAMP NOT NULL
);
CREATE INDEX idx_orders_buyer_id ON orders (buyer_id);
CREATE INDEX idx_orders_seller_id ON orders (seller_id);
CREATE INDEX idx_orders_order_status ON orders (order_status);
CREATE INDEX idx_orders_order_date ON orders (order_date DESC);
CREATE INDEX idx_orders_buyer_date ON orders (buyer_id, order_date DESC);
CREATE INDEX idx_orders_tracking_number ON orders (tracking_number);

-- ── order_items ──────────────────────────────────────────────────────────
CREATE TABLE order_items (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      BIGINT NOT NULL REFERENCES orders (id),
    product_id    BIGINT NOT NULL REFERENCES products (id),
    seller_id     BIGINT NOT NULL REFERENCES seller_profiles (id),
    quantity      INTEGER NOT NULL,
    unit_price    NUMERIC(10,2) NOT NULL,
    subtotal      NUMERIC(12,2) NOT NULL,
    item_status   VARCHAR(20) NOT NULL CHECK (item_status IN ('PENDING','CONFIRMED','PACKED','SHIPPED','DELIVERED','CANCELLED','RETURNED')),
    created_at    TIMESTAMP NOT NULL,
    updated_at    TIMESTAMP NOT NULL
);
CREATE INDEX idx_order_items_order_id ON order_items (order_id);
CREATE INDEX idx_order_items_seller_id ON order_items (seller_id);
CREATE INDEX idx_order_items_product_id ON order_items (product_id);

-- ── payments ─────────────────────────────────────────────────────────────
CREATE TABLE payments (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id               BIGINT NOT NULL REFERENCES orders (id),
    buyer_id               BIGINT NOT NULL REFERENCES users (id),
    amount                 NUMERIC(12,2) NOT NULL,
    currency               VARCHAR(3) NOT NULL,
    payment_method         VARCHAR(20) NOT NULL CHECK (payment_method IN ('CREDIT_CARD','DEBIT_CARD','BANK_TRANSFER','WALLET','OTHER')),
    payment_status         VARCHAR(20) NOT NULL CHECK (payment_status IN ('PENDING','COMPLETED','FAILED','REFUNDED')),
    transaction_id         VARCHAR(255) UNIQUE,
    payment_gateway        VARCHAR(50),
    payment_date           TIMESTAMP,
    refund_status          VARCHAR(20) NOT NULL CHECK (refund_status IN ('NOT_REFUNDED','PARTIALLY_REFUNDED','FULLY_REFUNDED')),
    total_refunded_amount  NUMERIC(12,2) NOT NULL,
    notes                  TEXT,
    created_at             TIMESTAMP NOT NULL,
    updated_at             TIMESTAMP NOT NULL
);
CREATE INDEX idx_payments_order_id ON payments (order_id);
CREATE INDEX idx_payments_buyer_id ON payments (buyer_id);
CREATE INDEX idx_payments_payment_status ON payments (payment_status);
CREATE INDEX idx_payments_transaction_id ON payments (transaction_id);
CREATE INDEX idx_payments_payment_date ON payments (payment_date DESC);

-- ── refunds ──────────────────────────────────────────────────────────────
CREATE TABLE refunds (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id             BIGINT NOT NULL REFERENCES payments (id),
    refund_amount          NUMERIC(12,2) NOT NULL,
    refund_reason          VARCHAR(100),
    refund_status          VARCHAR(20) NOT NULL CHECK (refund_status IN ('INITIATED','PENDING','COMPLETED','FAILED','DISPUTED')),
    refund_transaction_id  VARCHAR(255) UNIQUE,
    refund_date            TIMESTAMP,
    initiated_by_user_id   BIGINT REFERENCES users (id),
    notes                  TEXT,
    created_at             TIMESTAMP NOT NULL,
    updated_at             TIMESTAMP NOT NULL
);
CREATE INDEX idx_refunds_payment_id ON refunds (payment_id);
CREATE INDEX idx_refunds_refund_status ON refunds (refund_status);
CREATE INDEX idx_refunds_refund_date ON refunds (refund_date DESC);

-- ── reviews ──────────────────────────────────────────────────────────────
CREATE TABLE reviews (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id          BIGINT NOT NULL REFERENCES products (id),
    buyer_id            BIGINT NOT NULL REFERENCES users (id),
    order_item_id       BIGINT NOT NULL REFERENCES order_items (id),
    rating              INTEGER NOT NULL,
    review_title        VARCHAR(200),
    review_comment      TEXT,
    verified_purchase   BOOLEAN NOT NULL,
    helpful_count       INTEGER NOT NULL,
    seller_response     TEXT,
    seller_response_at  TIMESTAMP,
    review_status       VARCHAR(20) NOT NULL CHECK (review_status IN ('PENDING','APPROVED','REJECTED','HIDDEN')),
    is_locked           BOOLEAN NOT NULL,
    locked_at           TIMESTAMP,
    created_at          TIMESTAMP NOT NULL,
    updated_at          TIMESTAMP NOT NULL,
    deleted_at          TIMESTAMP,
    CONSTRAINT unique_review_per_user_product UNIQUE (product_id, buyer_id)
);
CREATE INDEX idx_reviews_product_id ON reviews (product_id);
CREATE INDEX idx_reviews_rating ON reviews (product_id, rating DESC);
CREATE INDEX idx_reviews_created_at ON reviews (product_id, created_at DESC);
CREATE INDEX idx_reviews_buyer_id ON reviews (buyer_id);
CREATE INDEX idx_reviews_is_locked ON reviews (product_id, is_locked);

-- ── disputes ─────────────────────────────────────────────────────────────
CREATE TABLE disputes (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dispute_number    VARCHAR(50) NOT NULL UNIQUE,
    order_id          BIGINT NOT NULL UNIQUE REFERENCES orders (id),
    buyer_id          BIGINT NOT NULL REFERENCES users (id),
    seller_id         BIGINT NOT NULL REFERENCES seller_profiles (id),
    initiated_by      VARCHAR(20) NOT NULL CHECK (initiated_by IN ('BUYER','SELLER')),
    dispute_reason    VARCHAR(100) NOT NULL,
    description       TEXT NOT NULL,
    evidence_urls     TEXT,
    dispute_status    VARCHAR(20) NOT NULL CHECK (dispute_status IN ('OPEN','IN_REVIEW','RESOLVED','CLOSED','APPEALED')),
    resolution        VARCHAR(20) NOT NULL CHECK (resolution IN ('REFUND','REPLACEMENT','CREDIT','NONE')),
    assigned_admin_id BIGINT REFERENCES users (id),
    admin_notes       TEXT,
    resolution_notes  TEXT,
    created_at        TIMESTAMP NOT NULL,
    resolved_at       TIMESTAMP,
    updated_at        TIMESTAMP NOT NULL
);
CREATE INDEX idx_disputes_order_id ON disputes (order_id);
CREATE INDEX idx_disputes_buyer_id ON disputes (buyer_id);
CREATE INDEX idx_disputes_seller_id ON disputes (seller_id);
CREATE INDEX idx_disputes_status ON disputes (dispute_status);
CREATE INDEX idx_disputes_created_at ON disputes (created_at DESC);
CREATE INDEX idx_disputes_assigned_admin_id ON disputes (assigned_admin_id);

-- ── audit_logs ───────────────────────────────────────────────────────────
CREATE TABLE audit_logs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT REFERENCES users (id),
    action       VARCHAR(50) NOT NULL,
    entity_type  VARCHAR(50) NOT NULL,
    entity_id    BIGINT NOT NULL,
    changes      JSON,
    ip_address   VARCHAR(45),
    user_agent   VARCHAR(500),
    timestamp    TIMESTAMP NOT NULL
);
CREATE INDEX idx_audit_logs_entity ON audit_logs (entity_type, entity_id);
CREATE INDEX idx_audit_logs_user_id ON audit_logs (user_id);
CREATE INDEX idx_audit_logs_action ON audit_logs (action);
CREATE INDEX idx_audit_logs_timestamp ON audit_logs (timestamp DESC);
CREATE INDEX idx_audit_logs_entity_time ON audit_logs (entity_type, entity_id, timestamp DESC);

-- ── outbox_events (Kafka transactional outbox) ─────────────────────────
CREATE TABLE outbox_events (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type    VARCHAR(50) NOT NULL,
    aggregate_id  BIGINT NOT NULL,
    payload       TEXT NOT NULL,
    status        VARCHAR(20) NOT NULL,
    created_at    TIMESTAMP NOT NULL,
    published_at  TIMESTAMP
);
CREATE INDEX idx_outbox_status_created ON outbox_events (status, created_at);
